-- ============================================
-- PARTNER SHARING
-- ============================================

-- Share links generated by Pro/Premium users
create table public.partner_share_links (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  token text unique not null,
  partner_name text,
  is_active boolean default true,
  expires_at timestamptz,
  last_accessed_at timestamptz,
  created_at timestamptz default now()
);

create index idx_partner_share_links_token on public.partner_share_links(token);
create index idx_partner_share_links_user_id on public.partner_share_links(user_id);

-- Lightweight reactions from partners on vendors
create table public.partner_reactions (
  id uuid default uuid_generate_v4() primary key,
  share_link_id uuid references public.partner_share_links(id) on delete cascade not null,
  vendor_id uuid references public.vendors(id) on delete cascade not null,
  partner_name text not null,
  reaction text not null check (reaction in ('thumbs_up', 'thumbs_down')),
  comment text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(share_link_id, vendor_id)
);

create index idx_partner_reactions_share_link on public.partner_reactions(share_link_id);
create index idx_partner_reactions_vendor_id on public.partner_reactions(vendor_id);

-- ── RLS ──────────────────────────────────────────────────────────────────────

alter table public.partner_share_links enable row level security;
alter table public.partner_reactions enable row level security;

-- Share links: only the owner can manage their links
create policy "Users can view their own share links"
  on public.partner_share_links for select
  using (auth.uid() = user_id);

create policy "Users can create share links"
  on public.partner_share_links for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own share links"
  on public.partner_share_links for update
  using (auth.uid() = user_id);

create policy "Users can delete their own share links"
  on public.partner_share_links for delete
  using (auth.uid() = user_id);

-- Reactions: owner can view reactions on their share links
create policy "Users can view reactions on their share links"
  on public.partner_reactions for select
  using (
    exists (
      select 1 from public.partner_share_links
      where id = partner_reactions.share_link_id
        and user_id = auth.uid()
    )
  );
